# tell travis that this is an objective-c project
language: objective-c

# install xcodetest dependencies
# before_install: 
    # ./install_dependencies.sh
    # - git submodule update --init --recursive 
    # - brew update
    # - brew install xctool

# build via xcodetest
script: ./build_and_run_unit_tests.sh MyApp MyAppTests
# script: xctool test -project Kiwi.xcodeproj -scheme Kiwi
